mpi:
  - nompi
  - openmpi  # [not win]
  - mpich  # [not win]

c_compiler:    # [win]
  - vs2019     # [win]

cxx_compiler:  # [win]
  - vs2019     # [win]

fortran_compiler_version:  # [win64]
  - 11  # [win64]
