{% set version = "4.4.4" %}
package:
    name: netcdf-fortran
    version: {{ version }}

source:
    fn: netcdf-fortran-{{ version }}.tar.gz
    url: https://github.com/Unidata/netcdf-fortran/archive/v{{ version }}.tar.gz
    sha256: 44b1986c427989604df9925dcdbf6c1a977e4ecbde6dd459114bca20bf5e9e67

build:
    number: 1
    skip: True  # [win]

requirements:
    build:
        - libnetcdf 4.4*
        - krb5
        - gcc
    run:
        - libnetcdf 4.4*
        - krb5
        - libgcc

test:
    commands:
        - nf-config --all
        - conda inspect linkages -n _test netcdf-fortran  # [linux]

about:
    home: https://github.com/Unidata/netcdf-fortran
    license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
    summary: Unidata NetCDF Fortran Library

extra:
    recipe-maintainers:
        - ocefpaf
        - bekozi
