{% set version = "4.5.2" %}

package:
  name: netcdf-fortran
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-fortran/archive/v{{ version }}.tar.gz
  sha256: 0b05c629c70d6d224a3be28699c066bfdfeae477aea211fbf034d973a8309b49
  patches:
    - no_clang.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cmake
    - pkg-config  # [not win]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - libnetcdf
    - hdf5

test:
  commands:
    - nf-config --help
    - test -f $PREFIX/lib/libnetcdf.a  # [not win]

about:
  home: https://github.com/Unidata/netcdf-fortran
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  license_file: COPYRIGHT
  summary: 'Unidata NetCDF Fortran Library'

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
    - beckermr
