{% set version = "4.5.2" %}
{% set build = 3 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: netcdf-fortran
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-fortran/archive/v{{ version }}.tar.gz
  sha256: 0b05c629c70d6d224a3be28699c066bfdfeae477aea211fbf034d973a8309b49
  patches:
    - no_clang.patch

build:
  number: {{ build }}
  skip: True  # [win]

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `netcdf-fortran * mpi_mpich_*` for mpich
  # `netcdf-fortran * mpi_*` for any mpi
  # `netcdf-fortran * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - cmake
    - make
    - pkg-config  # [not win]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}

  host:
    # need to list hdf5 and libnetcdf twice to get version pinning from conda_build_config
    # and build pinning from {{ mpi_prefix }}
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - libnetcdf * {{ mpi_prefix }}_*
    - hdf5 * {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']

test:
  commands:
    - nf-config --help
    - test -f $PREFIX/lib/libnetcdf.a  # [not win]

about:
  home: https://github.com/Unidata/netcdf-fortran
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  license_file: COPYRIGHT
  summary: 'Unidata NetCDF Fortran Library'

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
    - beckermr
    - xylar
