{% set version = "4.5.0" %}

package:
  name: netcdf-fortran
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-fortran/archive/v{{ version }}.tar.gz
  sha256: 23d60050e4bfded7c1f7ffc52b97949fa8f981dfaa138af88ba0d6e06586d8c0
  patches:
    - no_clang.patch  # [osx]

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cmake
    - pkg-config  # [not win]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - libnetcdf =4.7
    - hdf5

test:
  commands:
    #- nf-config --all  # FIXME: no nf-config for cmake
    - test -f ${PREFIX}/lib/libnetcdf.a  # [unix]

about:
  home: https://github.com/Unidata/netcdf-fortran
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  license_file: COPYRIGHT
  summary: 'Unidata NetCDF Fortran Library'

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
    - beckermr
