{% set version = "4.6.1" %}
{% set build = 3 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: netcdf-fortran
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-fortran/archive/v{{ version }}.tar.gz
  sha256: 40b534e0c81b853081c67ccde095367bd8a5eead2ee883431331674e7aa9509f
  patches:
    - 0001-no-clang.patch
    - manpage-quoting.patch
    - make-v2compat-cachable.patch
    - szip.patch  # [win]

build:
  number: {{ build }}
  merge_build_host: true  # [win]

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `netcdf-fortran * mpi_mpich_*` for mpich
  # `netcdf-fortran * mpi_*` for any mpi
  # `netcdf-fortran * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  {% if mpi != 'nompi' %}
  {% set build_pin = mpi_prefix + '_*' %}
  {% else %}
  {% set build_pin = '' %}
  {% endif %}

  run_exports:
    # https://abi-laboratory.pro/index.php?view=timeline&l=netcdf-fortran
    - {{ pin_subpackage('netcdf-fortran', max_pin='x.x') }} {{ build_pin }}

requirements:
  build:
    # General
    - cmake
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
    # Unix
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - make  # [unix]
    - pkg-config  # [unix]
    # Win
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - m2-make  # [win]
    - m2w64-pkg-config  # [win]
    - m2w64-dlfcn  # [win]
  host:
    # need to list hdf5 and libnetcdf twice to get version pinning from conda_build_config
    # and build pinning from {{ mpi_prefix }}
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - libnetcdf * {{ mpi_prefix }}_*
    - hdf5 * {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']

test:
  requires:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
  commands:
    - nf-config --version  # [not win]
    - test -f $(nf-config --fc)  # [not win]
    - test -f $PREFIX/lib/libnetcdff${SHLIB_EXT}  # [not win]
    # Check that libnetcdf's nc-config finds this package's nf-config
    - test -f $(nc-config --fc)  # [not win]
    # MinGW style import lib (.dll.a); check can be removed if we
    # switch to flang or similar, or if we decide to only ship .lib
    - if not exist %LIBRARY_LIB%/libnetcdff.dll.a exit 1  # [win]
    - if not exist %LIBRARY_LIB%/libnetcdff.lib exit 1  # [win]

about:
  home: https://github.com/Unidata/netcdf-fortran
  license: NetCDF
  license_file: COPYRIGHT
  summary: Unidata NetCDF Fortran Library

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
    - xylar
    - zklaus
