package:
    name: netcdf-fortran
    version: 4.4.3

source:
    git_url: https://github.com/Unidata/netcdf-fortran
    git_tag: v4.4.3

build:
    number: 3
    skip: True  # [win]

requirements:
    build:
        - libnetcdf 4.4.*
        - krb5
        - gcc
    run:
        - libnetcdf 4.4.*
        - krb5
        - libgcc

test:
    commands:
        - nf-config --all
        - conda inspect linkages -n _test netcdf-fortran  # [linux]

about:
    home: https://github.com/Unidata/netcdf-fortran
    license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
    summary: Unidata NetCDF Fortran Library

extra:
    recipe-maintainers:
        - ocefpaf
        - bekozi
