{% set version = "4.5.3" %}
{% set build = 3 %}

# recipe-lint fails if mpi is undefined
{% set mpi = mpi or 'nompi' %}
{% if mpi == "nompi" %}
# prioritize nompi via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: netcdf-fortran
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-fortran/archive/v{{ version }}.tar.gz
  sha256: c6da30c2fe7e4e614c1dff4124e857afbd45355c6798353eccfa60c0702b495a
  patches:
    - no_clang.patch

build:
  number: {{ build }}
  skip: true  # [win]
  merge_build_host: true

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `netcdf-fortran * mpi_mpich_*` for mpich
  # `netcdf-fortran * mpi_*` for any mpi
  # `netcdf-fortran * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  run_exports:
    # https://abi-laboratory.pro/index.php?view=timeline&l=netcdf-fortran
    - {{ pin_subpackage('netcdf-fortran', max_pin='x.x') }} {{ build_pin }}

requirements:
  build:
  host:
    - cmake
    - pkg-config  # [not win]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make  # [not win]
    # need to list hdf5 and libnetcdf twice to get version pinning from conda_build_config
    # and build pinning from {{ mpi_prefix }}
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - libnetcdf * {{ mpi_prefix }}_*
    - hdf5 * {{ mpi_prefix }}_*
    - {{ mpi }}  # [mpi != 'nompi']

test:
  requires:
    - {{ compiler('fortran') }}
  commands:
    - nf-config --help
    - test -f $(nc-config --fc)
    - test -f $PREFIX/lib/libnetcdf.a  # [not win]

about:
  home: https://github.com/Unidata/netcdf-fortran
  license: NetCDF
  license_file: COPYRIGHT
  summary: Unidata NetCDF Fortran Library

extra:
  recipe-maintainers:
    - ocefpaf
    - bekozi
    - xylar
